### ISSUE TITLE
Add a 💩 counter next to the ♥

### ISSUE THREAD

**Issue by Giszmo** [oslego/better-twitter#31]
I know, I know, this one would draw more attention than any of those others that Twitter might not even detect but hear me out :)

I would love to have a :hankey: counter that works as follows:

* If somebody replied to a tweet with only a negative emoji (:hankey:, :-1:, :facepalm: , maybe even gifs if there was an easy way of finding out from their alt text ...), increment the :hankey: counter.
* For every :heart: the :hankey: reply got, increment the :hankey: counter.
* Hide the :hankey: replies

The above would be almost in line with BT only hiding stuff. It only adds a counter of what was hidden.

Now of course I would love to pound that :hankey: button on occasion, so here BT probably gets out of its comfort zone: `likeFirstPooReply()` might still be harmless but `likeOrInitPooReply()` might be more delicate.

Please, if you close this issue, still give me a bit of feedback:

* If I fork BT with this feature, would it get killed in no time?
* Would it be hard to implement in the first place? I see you did already some gymnastics to work around Twitter's randomized class names, so maybe it's just no fun to maintain such a feature ...

**Comment by oslego** [comment]
> Please, if you close this issue, still give me a bit of feedback:
> - If I fork BT with this feature, would it get killed in no time?

Your intuition is right: this isn't a feature suitable to Better Twitter :) It wouldn't "get killed", just never merged.

I created this extension with the intent to remove distractions. The primary goal is to reduce mindless consumption and social media addiction.

The guiding principle regarding features for Better Twitter is subtractive, not additive. You're describing a feature which adds a layer of functionality.

> - Would it be hard to implement in the first place? I see you did already some gymnastics to work around Twitter's randomized class names, so maybe it's just no fun to maintain such a feature ...

Short answer is yes, this would require substantially more logic than Better Twitter. 

Consider:
- you need to identify context for emojis: in a tweet, a retweet,  etc
- you need to uniquely identify tweets
- you need to maintain local state of "processed" tweets and counters for "votes"
- you need to create a graph of tweets to tally up "votes" for the root tweet. 
From your requirements: "For every ❤️ the 💩 reply got, increment the 💩 counter."
- you need to hide only specific tweets based on contents. That's a tough nut to crack with the current Twitter markup.
 
It is non-trivial to implement. You may use code from Better Twitter as a source of inspiration, but this would ultimately have to be a separate extension.

It's not necessarily a bad idea. I'm not a fan, but what I think doesn't matter that much. If you feel it would solve a problem for you or even if it just entertains you and your friends, go ahead and try to build it. 

I built Better Twitter _for myself_ and shared it with others who might have the same needs. But I had no serious expectation of widespread use. Adoption of the extension points to a few people who wanted the same things so that validates my intuition a bit :)

It's important to work on something from which you derive joy intrinsically. It has to sustain you through frustrations with development, drab maintenance and the occasional negative user feedback. If this feature is it, you know what to do :)

**Comment by Giszmo** [comment]
Thank you for your kind words! And thank you for maintaining Better Twitter! Very much appreciated.
