### ISSUE TITLE
Hide replies in home feed

### ISSUE THREAD

**Issue by ImJezze** [oslego/better-twitter#32]
First of, i love your add-on! It makes the experience on Twitter much more clean.

I would like to make a request for an option to be able to hide replies, that are shown directly in my home feed.

e.g. Someone I subscribed to replied to someone I did not subscribe to.
![grafik](https://user-images.githubusercontent.com/11963815/116063651-80669600-a685-11eb-8c3c-8ec090d092e7.png)

**Comment by oslego** [comment]
Do you prefer to use the _Home_ feed instead of _Latest tweets_ (aka chronological feed)?

I ask because the "X replied" feature does not show up in _Latest tweets_. 

If you didn't know yet, you can switch the feed type by clicking the stars decoration at the top of the page:

![Screenshot 2021-04-26 at 12 01 33](https://user-images.githubusercontent.com/63899/116070591-1b16a300-a68d-11eb-98b0-3e97995a642d.jpg)

Altering the _Home_ feed is fighting a losing battle. That's where most of Twitter's experiments with boosting "engagement" happen.

**Comment by ImJezze** [comment]
Oh, I didn't know about that. I guess switching to Latest Tweets will solve my request then. Thanks!
